# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('communications', '0001_initial'),
        ('students', '0005_studentaccommodation_studentachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('fr', 'French'), ('other', 'Other')], default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='announcement',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional translated title/body objects keyed by language code.'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('consent_type', models.CharField(choices=[('media', 'Photo/video use'), ('trip', 'School trip'), ('medical', 'Medical support'), ('data', 'Data processing'), ('biometric', 'Attendance identity use'), ('counselling', 'Counselling support'), ('other', 'Other')], max_length=24)),
                ('policy_version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='consents/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_consents', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_consents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='students.student')),
            ],
            options={
                'ordering': ['-effective_date', 'student', 'consent_type'],
            },
        ),
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversation_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='conversation_threads', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='students.student')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('fr', 'French'), ('other', 'Other')], default='en', max_length=12)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='conversations/%Y/')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_conversation_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversationthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('fr', 'French'), ('other', 'Other')], default='en', max_length=12)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('advisory', 'Advisory'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='urgent', max_length=16)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('staff', 'All staff'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents'), ('stream', 'Selected stream')], default='all', max_length=20)),
                ('channels', models.JSONField(default=list, help_text='Delivery channels such as in_app, sms, email or whatsapp.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_summary', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ManyToManyField(blank=True, related_name='acknowledged_emergency_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergency_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emergency_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_broadcasts', to='academics.stream')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
