# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('required_room_type', models.CharField(blank=True, choices=[('', 'Any suitable room'), ('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('computer', 'Computer laboratory'), ('workshop', 'Workshop'), ('hall', 'Hall'), ('field', 'Sports field')], max_length=30)),
                ('allowed_days', models.JSONField(blank=True, default=list, help_text='Weekday numbers, for example [1,2,3,4,5]. Empty means Monday–Friday.')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_requirement', to='academics.subjectallocation')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_scheduling_requirements', to='timetables.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Completed with gaps'), ('simulated', 'Simulation'), ('failed', 'Failed')], default='running', max_length=20)),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_generation_runs', to='academics.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
