# Generated by Django 6.0.6 on 2026-07-01 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('students', '0002_enrollment_guardian_studentguardian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('movement_type', models.CharField(choices=[('transfer_in', 'Transferred in'), ('transfer_out', 'Transferred out'), ('withdrawal', 'Withdrawn'), ('suspension', 'Suspended'), ('reinstatement', 'Reinstated'), ('graduation', 'Graduated')], max_length=24)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('previous_school', models.CharField(blank=True, max_length=180)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('document', models.FileField(blank=True, null=True, upload_to='student-movements/%Y/')),
                ('authorised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_student_movements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='students.student')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('principal', 'Principal'), ('subsidiary', 'Subsidiary')], default='core', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('registered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('dropped_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='students.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_registrations', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('enrollment', 'subject'), name='unique_active_enrollment_subject')],
            },
        ),
    ]
