# Generated by Django 6.0.6 on 2026-07-02 06:05

from django.conf import settings
from django.db import migrations, models


def populate_student_numbers(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    for sequence, student in enumerate(Student.objects.filter(student_number__isnull=True).order_by("id"), 1):
        student.student_number = f"STU-{sequence:06d}"
        student.save(update_fields=["student_number"])


def clear_generated_student_numbers(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Student.objects.filter(student_number__startswith="STU-").update(student_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('students', '0003_studentmovement_studentsubjectregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Permanent learner identifier used across admission years.', max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(populate_student_numbers, clear_generated_student_numbers),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='students_st_student_0be38d_idx'),
        ),
    ]
