# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('learning', 'Learning support'), ('visual', 'Visual access'), ('hearing', 'Hearing access'), ('mobility', 'Mobility access'), ('medical', 'Medical support'), ('language', 'Language support'), ('assessment', 'Assessment access arrangement'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('need_description', models.TextField()),
                ('support_strategy', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Due for review'), ('ended', 'Ended')], default='active', max_length=20)),
                ('confidential', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_accommodations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_accommodations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='students.student')),
            ],
            options={
                'ordering': ['-start_date', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('project', 'Project'), ('leadership', 'Leadership'), ('sport', 'Sport'), ('arts', 'Creative arts'), ('vocational', 'Vocational'), ('community', 'Community service'), ('innovation', 'Innovation'), ('other', 'Other')], max_length=24)),
                ('achievement_date', models.DateField()),
                ('level', models.CharField(choices=[('school', 'School'), ('district', 'District'), ('regional', 'Regional'), ('national', 'National'), ('international', 'International')], default='school', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='student-achievements/%Y/')),
                ('external_reference', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achievement_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('creative', 'Creative arts'), ('sport', 'Sport'), ('vocational', 'Vocational'), ('technology', 'Technology'), ('community', 'Community service'), ('leadership', 'Leadership'), ('other', 'Other')], default='academic', max_length=24)),
                ('engagement_level', models.CharField(choices=[('exploring', 'Exploring'), ('active', 'Actively engaged'), ('advanced', 'Advanced')], default='exploring', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('first_observed', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_interests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='students.student')),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'name'), name='unique_active_student_interest')],
            },
        ),
    ]
