"""Idempotent demonstration data for the complete academic workflow."""

import os
from datetime import date, time
from decimal import Decimal

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from accounts.models import User
from academics.models import AcademicYear, CalendarEvent, ClassLevel, Department, SchoolProfile, Stream, Subject, SubjectAllocation, SubjectCombination, Term
from assessments.models import ActivityOfIntegration, Assessment, AssessmentPolicy, AssessmentResult, AssessmentType, Competency, CompetencyAssessment, CompetencyLevel, CurriculumFramework, CurriculumLearningArea, CurriculumTopic, CurriculumValue, LearningOutcome, Rubric, RubricCriterion, RubricLevel, Skill
from attendance.models import AttendanceRecord, AttendanceSession
from communications.models import Announcement, LearningResource
from exams.models import ExamSession, Examination, ExaminationResult, GradeBoundary, GradeScale, UNEBCandidate, UNEBCandidateSubject, UNEBContinuousAssessment
from reports.services import generate_stream_reports
from students.models import Enrollment, Guardian, Student, StudentGuardian, StudentSubjectRegistration
from timetables.models import Room, TimeSlot, TimetableEntry


def user(username, role, first, last, password):
    account, created = User.objects.get_or_create(username=username, defaults={"role": role, "first_name": first, "last_name": last, "email": f"{username}@school.test"})
    account.role, account.first_name, account.last_name, account.is_active = role, first, last, True
    if created or not account.has_usable_password():
        account.set_password(password)
    account.save()
    return account


admin = user("admin", "super_admin", "System", "Administrator", "Admin@2026")
headteacher = user("headteacher", "headteacher", "Grace", "Nabukenya", "School@2026")
dos = user("dos", "director_of_studies", "David", "Okello", "School@2026")
teacher = user("teacher", "teacher", "Sarah", "Namusoke", "Teacher@2026")
parent_user = user("parent", "parent", "Peter", "Kato", "Parent@2026")
student_user = user("student", "student", "Amina", "Nabirye", "Student@2026")

SchoolProfile.objects.update_or_create(
    pk=SchoolProfile.objects.first().pk if SchoolProfile.objects.exists() else None,
    defaults={
        "name": "Acacia Secondary School", "motto": "Competence, character and service",
        "emis_number": "UG-DEMO-2026", "centre_number": "U9999", "ownership": "private",
        "address": "Plot 12 Learning Avenue", "district": "Kampala", "phone": "+256 700 000000",
        "email": "academics@acacia.test", "headteacher_name": headteacher.get_full_name(),
        "report_footer": "This report is an official academic record generated by Acacia Secondary School.",
    },
)

AcademicYear.objects.update(is_current=False)
year, _ = AcademicYear.objects.update_or_create(name="2026", defaults={"start_date": date(2026, 2, 2), "end_date": date(2026, 12, 4), "is_current": True})
term_specs = [
    (1, "Term I", date(2026, 2, 2), date(2026, 5, 1), False),
    (2, "Term II", date(2026, 5, 25), date(2026, 8, 21), True),
    (3, "Term III", date(2026, 9, 14), date(2026, 12, 4), False),
]
for number, name, start, end, current in term_specs:
    if current:
        Term.objects.update(is_current=False)
    Term.objects.update_or_create(academic_year=year, number=number, defaults={"name": name, "start_date": start, "end_date": end, "is_current": current})
term = Term.objects.get(academic_year=year, number=2)

departments = {}
for name, code in [("Languages", "LAN"), ("Mathematics", "MAT"), ("Sciences", "SCI"), ("Humanities", "HUM"), ("Vocational Studies", "VOC"), ("Creative Arts", "ART")]:
    departments[name], _ = Department.objects.update_or_create(name=name, defaults={"code": code, "head": teacher if name == "Languages" else None})

classes = {}
for level in range(1, 7):
    classes[level], _ = ClassLevel.objects.update_or_create(name=f"S{level}", defaults={"level": level, "curriculum": "lower" if level <= 4 else "upper", "description": "Uganda lower-secondary competency-based curriculum" if level <= 4 else "Uganda upper-secondary programme"})

streams = {}
for level, class_level in classes.items():
    streams[level], _ = Stream.objects.update_or_create(name="A", class_level=class_level, academic_year=year, defaults={"class_teacher": teacher if level == 1 else None, "room_name": f"Block A · Room {level}", "capacity": 55})

subject_specs = [
    ("English Language", "ENG", "Languages", "core", "both"), ("Literature in English", "LIT", "Languages", "elective", "upper"),
    ("Kiswahili", "KIS", "Languages", "core", "lower"), ("Mathematics", "MTC", "Mathematics", "core", "both"),
    ("Biology", "BIO", "Sciences", "core", "both"), ("Chemistry", "CHE", "Sciences", "core", "both"),
    ("Physics", "PHY", "Sciences", "core", "both"), ("General Science", "GSC", "Sciences", "core", "lower"),
    ("Geography", "GEO", "Humanities", "core", "both"), ("History and Political Education", "HPE", "Humanities", "core", "lower"),
    ("History", "HIS", "Humanities", "elective", "upper"), ("Religious Education", "REL", "Humanities", "elective", "both"),
    ("ICT", "ICT", "Vocational Studies", "core", "both"), ("Entrepreneurship", "ENT", "Vocational Studies", "elective", "both"),
    ("Agriculture", "AGR", "Vocational Studies", "vocational", "both"), ("Technology and Design", "TAD", "Vocational Studies", "vocational", "lower"),
    ("Art and Design", "ART", "Creative Arts", "vocational", "both"), ("Performing Arts", "PA", "Creative Arts", "vocational", "lower"),
    ("Physical Education", "PE", "Creative Arts", "core", "lower"),
]
subjects = {}
for name, code, department, subject_type, curriculum in subject_specs:
    subjects[code], _ = Subject.objects.update_or_create(code=code, defaults={"name": name, "short_name": name, "department": departments[department], "subject_type": subject_type, "curriculum_level": curriculum, "pass_mark": 50})

pcm, _ = SubjectCombination.objects.update_or_create(code="PCM", defaults={"name": "Physics, Chemistry and Mathematics", "curriculum_level": "upper", "description": "Upper-secondary science combination"})
pcm.subjects.set([subjects["PHY"], subjects["CHE"], subjects["MTC"]])
for code in ["ENG", "MTC", "GSC", "GEO", "ICT"]:
    SubjectAllocation.objects.update_or_create(teacher=teacher, subject=subjects[code], stream=streams[1], term=term, defaults={"lessons_per_week": 5 if code in {"ENG", "MTC"} else 3})

guardian, _ = Guardian.objects.update_or_create(user=parent_user, defaults={"first_name": "Peter", "last_name": "Kato", "phone": "+256 772 123456", "email": "parent@school.test", "occupation": "Civil engineer", "address": "Kira, Wakiso"})
student = Student.objects.filter(first_name="Amina", last_name="Nabirye").first()
if student:
    student.user, student.parent, student.stream, student.status = student_user, parent_user, streams[1], "active"
    student.date_admitted = date(2026, 2, 2)
    student.save()
else:
    student = Student.objects.create(user=student_user, parent=parent_user, first_name="Amina", last_name="Nabirye", gender="female", date_of_birth=date(2012, 5, 4), stream=streams[1], date_admitted=date(2026, 2, 2), previous_school="Kampala Junior School", medical_information="No known chronic conditions")
StudentGuardian.objects.update_or_create(student=student, guardian=guardian, defaults={"relationship": "father", "is_primary": True})
Enrollment.objects.update_or_create(student=student, academic_year=year, defaults={"stream": streams[1], "roll_number": 1})
enrollment = Enrollment.objects.get(student=student, academic_year=year)
for code in ["ENG", "MTC", "GSC", "GEO", "ICT"]:
    StudentSubjectRegistration.objects.update_or_create(enrollment=enrollment, subject=subjects[code], defaults={"category": "core", "status": "active"})

competency_names = ["Critical Thinking and Problem Solving", "Creativity and Innovation", "Communication", "Cooperation and Self-directed Learning", "Mathematical Computation", "ICT Proficiency"]
Competency.objects.exclude(name__in=competency_names).update(is_active=False)
competencies = []
for order, name in enumerate(competency_names, 1):
    item, _ = Competency.objects.update_or_create(name=name, defaults={"code": f"GS{order}", "description": f"Integrated generic skill evidenced through subject learning outcomes: {name.lower()}.", "display_order": order, "scale": [], "assessment_mode": "integrated", "curriculum_stage": "both", "is_active": True})
    competencies.append(item)
levels = []
for order, (name, code, value, colour) in enumerate([("Beginning", "BEG", 1, "#f59e0b"), ("Developing", "DEV", 2, "#3b82f6"), ("Proficient", "PRO", 3, "#10b981"), ("Exemplary", "EXC", 4, "#8b5cf6")], 1):
    item, _ = CompetencyLevel.objects.update_or_create(code=code, defaults={"name": name, "numeric_value": value, "display_order": order, "colour": colour})
    levels.append(item)

lower_framework, _ = CurriculumFramework.objects.update_or_create(name="Lower Secondary Curriculum", stage="lower", defaults={"version": "NLSC", "implementation_year": 2020, "description": "NCDC competency-based Lower Secondary Curriculum organised around subject learning outcomes, generic skills and Activities of Integration."})
advanced_framework, _ = CurriculumFramework.objects.update_or_create(name="Aligned Advanced Secondary Curriculum", stage="advanced", defaults={"version": "2025 aligned curriculum", "implementation_year": 2025, "description": "Learner-centred Advanced Secondary Curriculum aligned to the competency-based Lower Secondary Curriculum."})
value_names = ["Respect for Humanity and Environment", "Honesty", "Justice and Fairness", "Hard Work for Self-reliance", "Integrity", "Creativity and Innovativeness", "Social Responsibility", "Social Harmony", "National Unity", "National Consciousness and Patriotism"]
values = []
for order, name in enumerate(value_names, 1):
    value, _ = CurriculumValue.objects.update_or_create(name=name, defaults={"display_order": order, "is_assessed": False})
    values.append(value)
for order, name in enumerate(["Research Skills", "Presentation Skills", "ICT Skills", "Leadership", "Practical Skills", "Entrepreneurship", "Communication Skills"], 1):
    Skill.objects.update_or_create(name=name, defaults={"code": f"SK{order}", "display_order": order, "is_active": True})
learning_area, _ = CurriculumLearningArea.objects.update_or_create(framework=lower_framework, subject=subjects["ENG"], sequence=1, defaults={"code": "ENG-COM", "name": "Communication", "description": "Oral, written and multimodal communication."})
topic, _ = CurriculumTopic.objects.update_or_create(framework=lower_framework, subject=subjects["ENG"], class_level=classes[1], term_number=2, sequence=1, defaults={"learning_area": learning_area, "code": "S1-ENG-T2-01", "title": "Community stories and communication", "description": "Learners communicate experiences and community knowledge through oral and written products.", "suggested_periods": 12})
if topic.learning_area_id != learning_area.pk:
    topic.learning_area = learning_area
    topic.save()
outcome, _ = LearningOutcome.objects.update_or_create(topic=topic, code="S1.ENG.2.1", defaults={"statement": "The learner communicates a coherent community story for a defined audience using appropriate oral and written language.", "assessment_criteria": "The story is coherent, accurate and adapted to the intended audience.", "suggested_activities": "Interview a community member, draft the story, peer-review it and present it orally.", "required_evidence": "Interview notes, written story, presentation observation and learner reflection.", "display_order": 1})
outcome.generic_skills.set([competencies[0], competencies[2], competencies[3]])
outcome.values.set([values[0], values[5], values[6]])
activity, _ = ActivityOfIntegration.objects.update_or_create(topic=topic, title="Our community story", defaults={"scenario": "Your community is preparing a cultural learning day, but stories from older residents have not been recorded for younger learners.", "task": "Work with peers to gather one community story, check its meaning and present it clearly to a Senior One audience.", "expected_product": "A short written story and a three-minute group presentation.", "teacher_guidance": "Use observation, learner conversation and the final product to triangulate evidence.", "suggested_duration_minutes": 160, "is_project": True, "is_published": True})
rubric, _ = Rubric.objects.update_or_create(activity=activity, defaults={"name": "Community story integration rubric", "subject": subjects["ENG"], "description": "Criterion-referenced rubric for the community communication activity.", "total_marks": 50})
criterion_specs = [("Accuracy and meaning", 15), ("Communication for audience", 15), ("Collaboration and process", 10), ("Quality of final product", 10)]
for order, (name, maximum) in enumerate(criterion_specs, 1):
    criterion, _ = RubricCriterion.objects.update_or_create(rubric=rubric, name=name, defaults={"maximum_score": maximum, "display_order": order})
    level_specs = [("Beginning", 0.25, "Shows limited evidence and requires sustained guidance."), ("Developing", 0.5, "Shows partial evidence with some guidance."), ("Proficient", 0.8, "Meets the expected outcome independently in the given context."), ("Exemplary", 1, "Exceeds the expected outcome with insight and consistency.")]
    for level_order, (level_name, fraction, descriptor) in enumerate(level_specs, 1):
        RubricLevel.objects.update_or_create(criterion=criterion, name=level_name, defaults={"score": Decimal(str(maximum)) * Decimal(str(fraction)), "descriptor": descriptor, "display_order": level_order})

lower_policy, _ = AssessmentPolicy.objects.update_or_create(name="S1 Internal Progress Policy 2026", academic_year=year, class_level=classes[1], defaults={"curriculum_stage": "lower", "purpose": "internal", "ongoing_weight": 40, "summative_weight": 60, "summative_frequency": "termly", "show_class_position": False, "requires_complete_marks": True, "notes": "Demonstration internal school policy; not a claim of UNEB weighting."})
for level in (5, 6):
    AssessmentPolicy.objects.update_or_create(name=f"S{level} Aligned Advanced Internal Policy 2026", academic_year=year, class_level=classes[level], defaults={"curriculum_stage": "advanced", "purpose": "internal", "ongoing_weight": 40, "summative_weight": 60, "summative_frequency": "annual", "show_class_position": False, "requires_complete_marks": True, "notes": "One school-based summative assessment annually; ongoing evidence comes from learning activities."})

assessment_types = {}
for category, name, weight in [("exercise", "Class Exercise", 10), ("test", "Topic Test", 20), ("assignment", "Assignment", 10), ("project", "Project", 15), ("practical", "Practical Work", 15), ("presentation", "Presentation", 10), ("group", "Group Work", 10), ("coursework", "Coursework", 10)]:
    assessment_types[category], _ = AssessmentType.objects.update_or_create(category=category, name=name, defaults={"code": category[:3].upper(), "weight": weight})
assessment, _ = Assessment.objects.update_or_create(title="Communication Skills Project", term=term, subject=subjects["ENG"], stream=streams[1], defaults={"assessment_type": assessment_types["project"], "created_by": teacher, "assigned_date": date(2026, 6, 15), "due_date": date(2026, 7, 10), "max_score": 50, "status": "published", "instructions": "Prepare and present a short community story in a group.", "topic": topic, "activity_of_integration": activity, "rubric": rubric, "assessment_period": "end_topic", "evidence_method": "triangulated"})
assessment.learning_outcomes.set([outcome])
AssessmentResult.objects.update_or_create(assessment=assessment, student=student, defaults={"score": Decimal("42"), "feedback": "Clear ideas and confident delivery.", "marked_by": teacher})
for index, competency in enumerate(competencies[:4]):
    CompetencyAssessment.objects.update_or_create(assessment=assessment, student=student, competency=competency, defaults={"scale_level": levels[2 if index < 3 else 3], "assessed_by": teacher, "comment": "Demonstrated during the group project."})

scale, _ = GradeScale.objects.update_or_create(name="Uganda School Percentage Scale", defaults={"curriculum_level": "general", "description": "Configurable internal school grading scale", "is_default": True})
for grade, minimum, maximum, points, descriptor in [("A", 80, 100, 1, "Outstanding"), ("B", 70, 79.99, 2, "Very good"), ("C", 60, 69.99, 3, "Good"), ("D", 50, 59.99, 4, "Basic achievement"), ("E", 0, 49.99, 5, "Below expectation")]:
    GradeBoundary.objects.update_or_create(scale=scale, grade=grade, defaults={"minimum_score": minimum, "maximum_score": maximum, "points": points, "descriptor": descriptor, "description": descriptor})
exam_session, _ = ExamSession.objects.update_or_create(term=term, name="Term II End-of-Term Examinations", defaults={"exam_type": "end", "start_date": date(2026, 8, 3), "end_date": date(2026, 8, 14), "status": "published", "grade_scale": scale})
exam, _ = Examination.objects.update_or_create(title="S1 English End-of-Term Examination", session=exam_session, subject=subjects["ENG"], stream=streams[1], defaults={"term": term, "exam_date": date(2026, 8, 4), "max_score": 100, "status": "published", "created_by": teacher, "approved_by": dos})
ExaminationResult.objects.update_or_create(examination=exam, student=student, defaults={"score": Decimal("78"), "teacher_remark": "A strong result; continue reading widely.", "marked_by": teacher, "approved": True})

attendance_session, _ = AttendanceSession.objects.update_or_create(term=term, stream=streams[1], date=date(2026, 7, 1), session_type="daily", subject=None, period_label="Morning", defaults={"taken_by": teacher, "status": "verified"})
AttendanceRecord.objects.update_or_create(session=attendance_session, student=student, defaults={"status": "present"})

for order, (name, start, end, slot_type) in enumerate([("Period 1", time(8, 0), time(8, 40), "lesson"), ("Period 2", time(8, 40), time(9, 20), "lesson"), ("Break", time(9, 20), time(9, 50), "break"), ("Period 3", time(9, 50), time(10, 30), "lesson"), ("Period 4", time(10, 30), time(11, 10), "lesson")], 1):
    TimeSlot.objects.update_or_create(name=name, defaults={"start_time": start, "end_time": end, "slot_type": slot_type, "display_order": order})
room, _ = Room.objects.update_or_create(name="S1 A Classroom", defaults={"code": "A1", "capacity": 60})
lesson_slots = list(TimeSlot.objects.filter(slot_type="lesson", is_deleted=False).order_by("display_order"))
for day in range(1, 6):
    for index, slot in enumerate(lesson_slots[:3]):
        subject = subjects[["ENG", "MTC", "GSC"][index]]
        TimetableEntry.objects.update_or_create(term=term, stream=streams[1], day_of_week=day, time_slot=slot, defaults={"subject": subject, "teacher": teacher, "room": room})

CalendarEvent.objects.update_or_create(term=term, title="Term II End-of-Term Examinations", defaults={"category": "exam", "start_date": date(2026, 8, 3), "end_date": date(2026, 8, 14), "description": "End-of-term assessment period."})
Announcement.objects.update_or_create(title="Welcome to the academic portal", defaults={"body": "Students and parents can now follow timetables, assignments, attendance and published report cards from one secure workspace.", "audience": "all", "is_pinned": True, "created_by": dos})
LearningResource.objects.update_or_create(title="S1 English Project Guide", subject=subjects["ENG"], class_level=classes[1], defaults={"description": "A guide to planning, researching and presenting the Term II communication project.", "resource_type": "notes", "external_url": "https://example.com/learning-resource", "uploaded_by": teacher})

s4_student, _ = Student.objects.update_or_create(first_name="Brian", last_name="Okello", defaults={"gender": "male", "date_of_birth": date(2009, 9, 12), "stream": streams[4], "date_admitted": date(2023, 2, 6), "status": "active"})
s4_enrollment, _ = Enrollment.objects.update_or_create(student=s4_student, academic_year=year, defaults={"stream": streams[4], "roll_number": 1})
for code in ["ENG", "MTC", "BIO", "CHE", "PHY", "GEO", "ICT"]:
    StudentSubjectRegistration.objects.update_or_create(enrollment=s4_enrollment, subject=subjects[code], defaults={"category": "core", "status": "active"})
SubjectAllocation.objects.update_or_create(teacher=teacher, subject=subjects["ENG"], stream=streams[4], term=term, defaults={"lessons_per_week": 5})
candidate, _ = UNEBCandidate.objects.update_or_create(student=s4_student, examination_level="uce", examination_year=2026, defaults={"index_number": "U9999/001", "centre_number": "U9999", "candidate_name": s4_student.full_name.upper(), "gender": s4_student.gender, "status": "registered", "verified_by": dos})
candidate_subject, _ = UNEBCandidateSubject.objects.update_or_create(candidate=candidate, subject=subjects["ENG"], defaults={"subject_code": subjects["ENG"].uneb_code or subjects["ENG"].code, "category": "core"})
UNEBContinuousAssessment.objects.update_or_create(candidate_subject=candidate_subject, class_level=classes[4], term=term, component="activity_integration", defaults={"raw_score": 76, "maximum_score": 100, "evidence_reference": "S4-ENG-T2-AOI-001", "status": "approved", "entered_by": teacher, "verified_by": dos, "approved_by": headteacher})

generate_stream_reports(streams[1], term, dos, lower_policy)
print("Academic demonstration data created successfully.")
print("Logins: admin/Admin@2026, dos/School@2026, teacher/Teacher@2026, parent/Parent@2026, student/Student@2026")
