# Generated by Django 6.0.6 on 2026-07-01 11:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/%Y/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('reviewed', 'Reviewed'), ('returned', 'Returned')], default='submitted', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('statement', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['competency', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('numeric_value', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('colour', models.CharField(default='#10b981', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order', 'numeric_value'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-assigned_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ['student__first_name', 'student__last_name']},
        ),
        migrations.AlterModelOptions(
            name='assessmenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='competencyassessment',
            options={'ordering': ['competency__display_order']},
        ),
        migrations.AlterUniqueTogether(
            name='competencyassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='assessment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assessments/%Y/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('moderated', 'Moderated')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='category',
            field=models.CharField(choices=[('exercise', 'Class exercise'), ('test', 'Test'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical work'), ('presentation', 'Presentation'), ('group', 'Group work'), ('coursework', 'Coursework')], default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competency',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='competency',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.assessmenttype'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='scale',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='assessments.competency'),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'student'), name='unique_active_assessment_result'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='competencyindicator',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_indicators', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='competencyindicator',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assessments.competency'),
        ),
        migrations.AddField(
            model_name='competencyindicator',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_indicators', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assessments', to='assessments.competencyindicator'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='scale_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='assessments.competencylevel'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'student', 'competency'), name='unique_active_competency_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'student'), name='unique_active_assessment_submission'),
        ),
    ]
