# Generated by Django 6.0.6 on 2026-07-01 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('assessments', '0002_assessmentsubmission_competencyindicator_and_more'),
        ('students', '0002_enrollment_guardian_studentguardian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOfIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=180)),
                ('scenario', models.TextField()),
                ('task', models.TextField()),
                ('expected_product', models.TextField(blank=True)),
                ('teacher_guidance', models.TextField(blank=True)),
                ('suggested_duration_minutes', models.PositiveIntegerField(default=80)),
                ('is_project', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['topic', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=160)),
                ('stage', models.CharField(choices=[('lower', 'Lower Secondary'), ('advanced', 'Advanced Secondary')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('implementation_year', models.PositiveIntegerField(default=2025)),
                ('authority', models.CharField(default='National Curriculum Development Centre', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['stage', '-implementation_year'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_assessed', models.BooleanField(default=False, help_text='NCDC values inform learning but are not scored like knowledge and skills.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_period',
            field=models.CharField(choices=[('ongoing', 'Ongoing formative'), ('end_topic', 'End-of-topic integration'), ('annual', 'Annual school summative'), ('end_cycle', 'End-of-cycle certification')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='evidence_method',
            field=models.CharField(choices=[('observation', 'Observation'), ('conversation', 'Conversation'), ('product', 'Product'), ('triangulated', 'Triangulated evidence')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_summative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competency',
            name='assessment_mode',
            field=models.CharField(choices=[('integrated', 'Integrated into learning outcomes'), ('standalone', 'Standalone')], default='integrated', max_length=20),
        ),
        migrations.AddField(
            model_name='competency',
            name='curriculum_stage',
            field=models.CharField(choices=[('lower', 'Lower Secondary'), ('advanced', 'Advanced Secondary'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='activity_of_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.activityofintegration'),
        ),
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('observation', 'Observation'), ('conversation', 'Conversation'), ('product', 'Product')], max_length=20)),
                ('note', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assessment-evidence/%Y/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='assessments.assessment')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_assessment_evidence', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_evidence', to='students.student')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=160)),
                ('curriculum_stage', models.CharField(choices=[('lower', 'Lower Secondary'), ('advanced', 'Advanced Secondary')], max_length=20)),
                ('purpose', models.CharField(choices=[('internal', 'Internal reporting'), ('uneb', 'UNEB preparation')], default='internal', max_length=20)),
                ('ongoing_weight', models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summative_weight', models.DecimalField(decimal_places=2, default=60, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summative_frequency', models.CharField(choices=[('termly', 'Termly'), ('annual', 'Once per year'), ('none', 'No separate summative exam')], default='termly', max_length=20)),
                ('show_class_position', models.BooleanField(default=False)),
                ('requires_complete_marks', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_policies', to='academics.academicyear')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_policies', to='academics.classlevel')),
            ],
            options={
                'ordering': ['academic_year', 'class_level__level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term I'), (2, 'Term II'), (3, 'Term III')], default=1)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('suggested_periods', models.PositiveSmallIntegerField(default=1)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_topics', to='academics.classlevel')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='assessments.curriculumframework')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_topics', to='academics.subject')),
            ],
            options={
                'ordering': ['class_level__level', 'subject__name', 'term_number', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='activityofintegration',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_activities', to='assessments.curriculumtopic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.curriculumtopic'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('statement', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('generic_skills', models.ManyToManyField(blank=True, related_name='learning_outcomes', to='assessments.competency')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='assessments.curriculumtopic')),
                ('values', models.ManyToManyField(blank=True, related_name='learning_outcomes', to='assessments.curriculumvalue')),
            ],
            options={
                'ordering': ['topic', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='assessments.learningoutcome'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='assessments.activityofintegration')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='academics.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.rubric'),
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.rubric')),
            ],
            options={
                'ordering': ['rubric', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('descriptor', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='assessments.rubriccriterion')),
            ],
            options={
                'ordering': ['criterion', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RubricRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=180)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='assessments.rubriccriterion')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='assessments.rubriclevel')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_ratings', to='assessments.assessmentresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculumtopic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('framework', 'subject', 'class_level', 'term_number', 'sequence'), name='unique_active_curriculum_topic_sequence'),
        ),
        migrations.AddConstraint(
            model_name='rubricrating',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('result', 'criterion'), name='unique_active_result_rubric_criterion'),
        ),
    ]
