# Generated by Django 6.0.6 on 2026-07-02 20:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def group_existing_levels(apps, schema_editor):
    AssessmentScale = apps.get_model('assessments', 'AssessmentScale')
    CompetencyLevel = apps.get_model('assessments', 'CompetencyLevel')
    AssessmentPolicy = apps.get_model('assessments', 'AssessmentPolicy')
    LearningOutcomeAssessment = apps.get_model('assessments', 'LearningOutcomeAssessment')
    scale, _ = AssessmentScale.objects.get_or_create(
        name='Imported school achievement scale',
        defaults={
            'code': 'IMPORTED',
            'description': 'Created during migration to preserve the school achievement levels already in use.',
            'is_default': True,
            'is_active': True,
        },
    )
    AssessmentScale.objects.exclude(pk=scale.pk).update(is_default=False)
    CompetencyLevel.objects.filter(scale__isnull=True).update(scale=scale)
    AssessmentPolicy.objects.filter(achievement_scale__isnull=True).update(achievement_scale=scale)

    levels = list(CompetencyLevel.objects.filter(scale=scale).order_by('numeric_value', 'display_order', 'pk'))
    if levels:
        positions = {
            'needs_support': levels[0],
            'approaching': levels[min(1, len(levels) - 1)],
            'met': levels[max(0, len(levels) - 2)],
            'exceeded': levels[-1],
        }
        for legacy_code, target in positions.items():
            LearningOutcomeAssessment.objects.filter(level=legacy_code, scale_level__isnull=True).update(scale_level=target)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('assessments', '0004_skill_assessment_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='project_subjects',
            field=models.ManyToManyField(blank=True, related_name='interdisciplinary_projects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='project_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='project_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual project'), ('group', 'Group project'), ('class', 'Class project'), ('interdisciplinary', 'Interdisciplinary project'), ('long_term', 'Long-term project'), ('community', 'Community project')], max_length=24),
        ),
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional weight for this task. When blank, the assessment type's default weight is used.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='reporting weight'),
        ),
        migrations.AddField(
            model_name='learningoutcomeassessment',
            name='scale_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_outcome_assessments', to='assessments.competencylevel'),
        ),
        migrations.AlterField(
            model_name='curriculumframework',
            name='implementation_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='learningoutcomeassessment',
            name='level',
            field=models.CharField(blank=True, help_text='Legacy code snapshot; new ratings use the configured scale level.', max_length=24),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='achievement_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='assessments.assessmentscale'),
        ),
        migrations.AddField(
            model_name='competencylevel',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='assessments.assessmentscale'),
        ),
        migrations.RunPython(group_existing_levels, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('expected_evidence', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('open', 'Open'), ('closed', 'Closed')], default='planned', max_length=16)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='assessments.assessment')),
            ],
            options={
                'ordering': ['assessment', 'sequence', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='assessments.projectmilestone'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'sequence'), name='unique_active_project_milestone_sequence'),
        ),
    ]
