# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentscale_assessment_project_subjects_and_more'),
        ('students', '0005_studentaccommodation_studentachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentevidence',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='evidence_records', to='assessments.competency'),
        ),
        migrations.AddField(
            model_name='assessmentevidence',
            name='context_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentevidence',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='evidence_records', to='assessments.learningoutcome'),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_curriculum_frameworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='source_reference',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='curriculumframework',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_versions', to='assessments.curriculumframework'),
        ),
        migrations.CreateModel(
            name='EvidenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('link', 'External link'), ('text', 'Text note')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='assessment-evidence/assets/%Y/')),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('transcript', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_evidence_assets', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assessments.assessmentevidence')),
            ],
            options={
                'ordering': ['captured_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('driving_question', models.TextField(blank=True)),
                ('community_partner', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='forming', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='assessments.assessment')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_project_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assessment', 'name'],
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='assessments.projectteam'),
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('contribution_notes', models.TextField(blank=True)),
                ('learner_reflection', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='students.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assessments.projectteam')),
            ],
            options={
                'ordering': ['team', 'student__first_name', 'student__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectteam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'name'), name='unique_active_project_team_name'),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('team', 'student'), name='unique_active_project_team_member'),
        ),
    ]
