# Generated by Django 6.0.6 on 2026-07-05 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_finance_budget',
        ),
        migrations.RemoveConstraint(
            model_name='budgetline',
            name='unique_budget_department_category',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', True)), fields=('name', 'academic_year'), name='unique_annual_finance_budget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', False)), fields=('name', 'academic_year', 'term'), name='unique_term_finance_budget'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('budget', 'category'), name='unique_general_budget_category'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('budget', 'department', 'category'), name='unique_department_budget_category'),
        ),
    ]
