# Generated by Django 6.0.6 on 2026-07-05 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('staff_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='NIN')),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/%Y/')),
                ('job_title', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part time'), ('volunteer', 'Volunteer')], default='permanent', max_length=20)),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_teaching_staff', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('leave', 'On leave'), ('suspended', 'Suspended'), ('former', 'Former staff')], default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academics.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('contract', 'Employment contract'), ('identity', 'Identity document'), ('qualification', 'Academic qualification'), ('appointment', 'Appointment letter'), ('other', 'Other')], default='other', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='staff/documents/%Y/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=60)),
                ('mobile_money_number', models.CharField(blank=True, max_length=30)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='staff.staffmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['staff_number'], name='staff_staff_staff_n_51274f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['status', 'department'], name='staff_staff_status_4b58b0_idx'),
        ),
    ]
