# Generated by Django 6.0.6 on 2026-07-05 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('students', '0005_studentaccommodation_studentachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('boarding', 'Boarding'), ('meals', 'Meals'), ('uniform', 'Uniform'), ('transport', 'Transport'), ('examination', 'Examination'), ('activity', 'Activity'), ('development', 'Development'), ('other', 'Other')], default='tuition', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.classlevel')),
                ('stream', models.ForeignKey(blank=True, help_text='Leave empty to apply to every stream in this class level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.stream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.term')),
            ],
            options={
                'ordering': ['-term__academic_year__start_date', 'class_level__level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_items', to='fees.feeitem')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure')),
            ],
            options={
                'ordering': ['fee_item__category', 'fee_item__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Part paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='students.enrollment')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_invoices', to='academics.term')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank deposit'), ('mobile_money', 'Mobile money'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.studentinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=180)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='fees.feeitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fees.studentinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('waiver', 'Waiver'), ('credit', 'Credit'), ('charge', 'Additional charge')], max_length=16)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_adjustments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fees.studentinvoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('name', 'term', 'class_level', 'stream'), name='unique_fee_structure_scope'),
        ),
        migrations.AddConstraint(
            model_name='feestructureitem',
            constraint=models.UniqueConstraint(fields=('structure', 'fee_item'), name='unique_fee_item_per_structure'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['invoice_number'], name='fees_studen_invoice_a39b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['status', 'due_date'], name='fees_studen_status_f69902_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='fees_paymen_receipt_755eab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'is_reversed'], name='fees_paymen_payment_7053b3_idx'),
        ),
    ]
