# Generated by Django 6.0.6 on 2026-07-05 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('fees', '0001_initial'),
        ('students', '0005_studentaccommodation_studentachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feestructure',
            name='unique_fee_structure_scope',
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', True)), fields=('name', 'term', 'class_level'), name='unique_fee_structure_all_streams'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False)), fields=('name', 'term', 'class_level', 'stream'), name='unique_fee_structure_stream'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('structure__isnull', False)), fields=('student', 'structure'), name='unique_active_structure_invoice'),
        ),
    ]
