# Generated by Django 6.0.6 on 2026-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_activity_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('fr', 'French'), ('other', 'Other')], default='en', max_length=12),
        ),
    ]
