# Generated by Django 6.0.6 on 2026-07-01 11:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('exam_type', models.CharField(choices=[('bot', 'Beginning of term'), ('mid', 'Mid term'), ('end', 'End of term'), ('mock', 'Mock examination'), ('external', 'External examination')], default='end', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('entry', 'Mark entry'), ('moderation', 'Moderation'), ('approved', 'Approved'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('curriculum_level', models.CharField(choices=[('lower', 'Lower Secondary CBC'), ('upper', 'Upper Secondary'), ('general', 'General')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-exam_date', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='examinationresult',
            options={'ordering': ['student__first_name', 'student__last_name']},
        ),
        migrations.AlterModelOptions(
            name='gradeboundary',
            options={'ordering': ['-minimum_score']},
        ),
        migrations.AddField(
            model_name='examination',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='examination',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_examinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('entry', 'Mark entry'), ('submitted', 'Submitted'), ('moderated', 'Moderated'), ('approved', 'Approved'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='examination',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='examination',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='descriptor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='moderated_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='teacher_remark',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='descriptor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examination',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='examination',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='examinationresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('examination', 'student'), name='unique_active_examination_result'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='academics.term'),
        ),
        migrations.AddField(
            model_name='examination',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='grade_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='exams.gradescale'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='exams.gradescale'),
        ),
    ]
