# Generated by Django 6.0.6 on 2026-07-01 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('exams', '0002_examsession_gradescale_alter_examination_options_and_more'),
        ('students', '0002_enrollment_guardian_studentguardian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='is_school_summative',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('bot', 'Beginning of term'), ('mid', 'Mid term'), ('end', 'End of term'), ('annual', 'Annual school summative'), ('mock', 'Mock examination'), ('external', 'External/end-of-cycle examination')], default='end', max_length=30),
        ),
        migrations.CreateModel(
            name='UNEBCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('examination_level', models.CharField(choices=[('uce', 'UCE'), ('uace', 'UACE')], max_length=10)),
                ('examination_year', models.PositiveIntegerField()),
                ('index_number', models.CharField(blank=True, max_length=40)),
                ('centre_number', models.CharField(max_length=30)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('registered', 'Registered'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uneb_candidates', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_uneb_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['examination_year', 'examination_level', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='UNEBCandidateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('principal', 'Principal'), ('subsidiary', 'Subsidiary')], default='core', max_length=20)),
                ('is_registered', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_subjects', to='exams.unebcandidate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uneb_candidate_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='UNEBContinuousAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('component', models.CharField(choices=[('subject_achievement', 'Subject achievement'), ('activity_integration', 'Activity of Integration'), ('project', 'Project'), ('coursework', 'Coursework')], max_length=30)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('percentage_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evidence_reference', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('approved', 'Approved'), ('exported', 'Exported')], default='draft', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_uneb_ca', to=settings.AUTH_USER_MODEL)),
                ('candidate_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_assessments', to='exams.unebcandidatesubject')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uneb_ca_records', to='academics.classlevel')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_uneb_ca', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uneb_ca_records', to='academics.term')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_uneb_ca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['candidate_subject__candidate__candidate_name', 'candidate_subject__subject__name', 'class_level__level', 'term__number'],
            },
        ),
        migrations.CreateModel(
            name='UNEBExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('examination_level', models.CharField(choices=[('uce', 'UCE'), ('uace', 'UACE')], max_length=10)),
                ('examination_year', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('submitted', 'Submitted externally'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uneb_export_batches', to=settings.AUTH_USER_MODEL)),
                ('records', models.ManyToManyField(blank=True, related_name='export_batches', to='exams.unebcontinuousassessment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='unebcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'examination_level', 'examination_year'), name='unique_active_uneb_candidate'),
        ),
        migrations.AddConstraint(
            model_name='unebcandidatesubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('candidate', 'subject'), name='unique_active_uneb_candidate_subject'),
        ),
        migrations.AddConstraint(
            model_name='unebcontinuousassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('candidate_subject', 'class_level', 'term', 'component'), name='unique_active_uneb_ca_component'),
        ),
    ]
