# Generated by Django 6.0.6 on 2026-07-02 06:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('exams', '0003_examination_is_school_summative_and_more'),
        ('students', '0003_studentmovement_studentsubjectregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpperAssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('component_type', models.CharField(choices=[('bot', 'Beginning of term test'), ('midterm', 'Midterm'), ('coursework', 'Coursework'), ('practical', 'Practical'), ('project', 'Project'), ('research', 'Research'), ('laboratory', 'Laboratory records'), ('fieldwork', 'Field work'), ('exam', 'End of term examination'), ('holiday', 'Holiday test')], max_length=24)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['plan', 'sequence', 'name'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('bot', 'Beginning of term'), ('mid', 'Mid term'), ('coursework', 'Coursework'), ('practical', 'Practical'), ('project', 'Project'), ('holiday', 'Holiday test'), ('end', 'End of term'), ('annual', 'Annual school summative'), ('mock', 'Mock examination'), ('external', 'External/end-of-cycle examination')], default='end', max_length=30),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='examination',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='exams.upperassessmentcomponent'),
        ),
        migrations.CreateModel(
            name='UpperAssessmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=160)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_assessment_plans', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_upper_assessment_plans', to=settings.AUTH_USER_MODEL)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_assessment_plans', to='academics.classlevel')),
                ('grade_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upper_assessment_plans', to='exams.gradescale')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_assessment_plans', to='academics.subject')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'class_level__level', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='upperassessmentcomponent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='exams.upperassessmentplan'),
        ),
        migrations.CreateModel(
            name='UpperSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('component_breakdown', models.JSONField(blank=True, default=dict)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('passed', models.BooleanField(default=False)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_position', models.PositiveIntegerField(blank=True, null=True)),
                ('has_missing_components', models.BooleanField(default=False)),
                ('missing_components', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('moderated', 'Moderated'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_results', to='exams.upperassessmentplan')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_upper_results', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_subject_results', to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_subject_results', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upper_subject_results', to='academics.term')),
            ],
            options={
                'ordering': ['plan__subject__name', 'student__first_name', 'student__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='upperassessmentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('academic_year', 'class_level', 'subject'), name='unique_active_upper_assessment_plan'),
        ),
        migrations.AddConstraint(
            model_name='upperassessmentcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('plan', 'name'), name='unique_active_upper_plan_component_name'),
        ),
        migrations.AddConstraint(
            model_name='uppersubjectresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('plan', 'student', 'term'), name='unique_active_upper_student_subject_result'),
        ),
    ]
