# Generated by Django 6.0.6 on 2026-07-03 11:54

from django.db import migrations, models


def normalise_aligned_components(apps, schema_editor):
    Component = apps.get_model("exams", "UpperAssessmentComponent")
    Plan = apps.get_model("exams", "UpperAssessmentPlan")
    legacy = Component.objects.filter(component_type__in=("bot", "midterm", "exam", "holiday"))
    plan_ids = list(legacy.values_list("plan_id", flat=True).distinct())
    Component.objects.filter(component_type="exam").update(component_type="annual_summative")
    Component.objects.filter(component_type__in=("bot", "midterm", "holiday")).update(component_type="coursework")
    for plan in Plan.objects.filter(pk__in=plan_ids):
        notice = "Legacy term-test components were normalised during the aligned S5/S6 migration; review and re-approve this plan."
        plan.status = "draft"
        plan.approved_by_id = None
        plan.approved_at = None
        plan.notes = f"{plan.notes}\n{notice}".strip()
        plan.save(update_fields=["status", "approved_by", "approved_at", "notes"])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_normalize_examination_flags'),
    ]

    operations = [
        migrations.RunPython(normalise_aligned_components, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='upperassessmentcomponent',
            name='component_type',
            field=models.CharField(choices=[('activity_integration', 'Activity of Integration'), ('coursework', 'Coursework'), ('practical', 'Practical'), ('project', 'Project-based learning'), ('research', 'Research'), ('laboratory', 'Laboratory records'), ('fieldwork', 'Field work'), ('annual_summative', 'Annual school summative assessment')], max_length=24),
        ),
    ]
