# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_upperassessmentcomponent_component_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unebexportbatch',
            name='format_version',
            field=models.CharField(default='internal-pre-submission-v1', max_length=40),
        ),
        migrations.AddField(
            model_name='unebexportbatch',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UNEBIntegrationAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=160)),
                ('examination_level', models.CharField(choices=[('uce', 'UCE'), ('uace', 'UACE')], max_length=10)),
                ('version', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('columns', models.JSONField(blank=True, default=list, help_text='Ordered objects with header and key values.')),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_uneb_adapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['examination_level', '-effective_from', '-version'],
            },
        ),
        migrations.AddField(
            model_name='unebexportbatch',
            name='adapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_batches', to='exams.unebintegrationadapter'),
        ),
        migrations.AddConstraint(
            model_name='unebintegrationadapter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('examination_level', 'version'), name='unique_active_uneb_adapter_version'),
        ),
    ]
