# Generated by Django 6.0.6 on 2026-07-01 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('assessments', '0002_assessmentsubmission_competencyindicator_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ca_weight', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='continuous assessment weight')),
                ('exam_weight', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_size', models.PositiveIntegerField(default=0)),
                ('attendance_present', models.PositiveIntegerField(default=0)),
                ('attendance_absent', models.PositiveIntegerField(default=0)),
                ('attendance_late', models.PositiveIntegerField(default=0)),
                ('teacher_remark', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('promotion_decision', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('repeated', 'Repeat class'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_cards', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.term')),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=180)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_ratings', to='assessments.competency')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_ratings', to='assessments.competencylevel')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='reports.reportcard')),
            ],
            options={
                'ordering': ['competency__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('continuous_assessment_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('examination_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=120)),
                ('subject_position', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_remark', models.CharField(blank=True, max_length=180)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='reports.reportcard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_results', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'term'), name='unique_active_student_term_report'),
        ),
        migrations.AddConstraint(
            model_name='reportcompetencyrating',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'competency'), name='unique_active_report_competency'),
        ),
        migrations.AddConstraint(
            model_name='reportsubjectresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'subject'), name='unique_active_report_subject'),
        ),
    ]
