# Generated by Django 6.0.6 on 2026-07-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_activityofintegration_curriculumframework_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='assessment_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='assessments.assessmentpolicy'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='has_missing_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='missing_mark_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportsubjectresult',
            name='missing_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='reportsubjectresult',
            name='ongoing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportsubjectresult',
            name='summative_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportsubjectresult',
            name='summative_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectresult',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
