# Generated by Django 6.0.6 on 2026-07-02 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_calendarevent_schoolprofile_and_more'),
        ('assessments', '0004_skill_assessment_submitted_at_and_more'),
        ('reports', '0002_reportcard_assessment_policy_and_more'),
        ('students', '0003_studentmovement_studentsubjectregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='dos_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='portfolio_summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AcademicTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('void', 'Void')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transcripts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_transcripts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLearningOutcomeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('exceeded', 'Exceeded expectation'), ('met', 'Met expectation'), ('approaching', 'Approaching expectation'), ('needs_support', 'Needs support')], max_length=24)),
                ('comment', models.CharField(blank=True, max_length=180)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_ratings', to='assessments.learningoutcome')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_ratings', to='reports.reportcard')),
            ],
            options={
                'ordering': ['outcome__topic__subject__name', 'outcome__display_order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'outcome'), name='unique_active_report_learning_outcome')],
            },
        ),
        migrations.CreateModel(
            name='ReportSkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=180)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_skill_ratings', to='assessments.competencylevel')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='reports.reportcard')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_ratings', to='assessments.skill')),
            ],
            options={
                'ordering': ['skill__display_order', 'skill__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'skill'), name='unique_active_report_skill')],
            },
        ),
        migrations.CreateModel(
            name='ReportValueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=180)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_value_ratings', to='assessments.competencylevel')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_ratings', to='reports.reportcard')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_ratings', to='assessments.curriculumvalue')),
            ],
            options={
                'ordering': ['value__display_order', 'value__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'value'), name='unique_active_report_value')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=180)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_entries', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_entries', to='academics.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_entries', to='academics.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcript_entries', to='academics.term')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.academictranscript')),
            ],
            options={
                'ordering': ['academic_year__start_date', 'term__number', 'subject__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('transcript', 'academic_year', 'term', 'subject'), name='unique_active_transcript_term_subject')],
            },
        ),
    ]
