# Generated by Django 6.0.6 on 2026-07-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentscale_assessment_project_subjects_and_more'),
        ('reports', '0003_reportcard_dos_remark_reportcard_portfolio_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlearningoutcomerating',
            name='scale_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_learning_outcome_ratings', to='assessments.competencylevel'),
        ),
        migrations.AlterField(
            model_name='reportlearningoutcomerating',
            name='level',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
