# Generated by Django 6.0.6 on 2026-07-01 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectcombination',
            name='subjects',
            field=models.ManyToManyField(related_name='combinations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('teacher', 'subject', 'stream', 'term')},
        ),
    ]
