# Generated by Django 6.0.6 on 2026-07-01 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def assign_term_numbers(apps, schema_editor):
    Term = apps.get_model('academics', 'Term')
    year_ids = Term.objects.values_list('academic_year_id', flat=True).distinct()
    for year_id in year_ids:
        for number, term in enumerate(Term.objects.filter(academic_year_id=year_id).order_by('start_date', 'pk'), 1):
            term.number = min(number, 3)
            term.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('exam', 'Examination'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('activity', 'School activity')], default='academic', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='My Secondary School', max_length=180)),
                ('motto', models.CharField(blank=True, max_length=180)),
                ('emis_number', models.CharField(blank=True, max_length=40, verbose_name='EMIS number')),
                ('centre_number', models.CharField(blank=True, max_length=40, verbose_name='UNEB centre number')),
                ('ownership', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community'), ('faith', 'Faith-based')], default='private', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('headteacher_name', models.CharField(blank=True, max_length=120)),
                ('report_footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'school profile',
            },
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['class_level__level', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subjectallocation',
            options={'ordering': ['stream__class_level__level', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='subjectcombination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-academic_year__start_date', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='capacity',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='room_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('subsidiary', 'Subsidiary'), ('vocational', 'Vocational')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='uneb_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='UNEB code'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='lessons_per_week',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='subjectcombination',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subjectcombination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectcombination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='term',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term I'), (2, 'Term II'), (3, 'Term III')], default=1),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='curriculum',
            field=models.CharField(choices=[('lower', 'Lower Secondary CBC'), ('upper', 'Upper Secondary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='level',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.classlevel'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to='academics.stream'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to='academics.term'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='curriculum_level',
            field=models.CharField(choices=[('lower', 'Lower Secondary'), ('upper', 'Upper Secondary')], default='upper', max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'class_level', 'academic_year'), name='unique_active_stream'),
        ),
        migrations.AddConstraint(
            model_name='subjectallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('teacher', 'subject', 'stream', 'term'), name='unique_active_subject_allocation'),
        ),
        migrations.RunPython(assign_term_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('academic_year', 'number'), name='unique_active_term_number'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.term'),
        ),
    ]
