# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_capture_ids(apps, schema_editor):
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    for record in AttendanceRecord.objects.filter(capture_id__isnull=True).iterator():
        record.capture_id = uuid.uuid4()
        record.save(update_fields=['capture_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_status'),
        ('students', '0005_studentaccommodation_studentachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='capture_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_capture_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancerecord',
            name='capture_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('web', 'Web register'), ('offline', 'Offline device'), ('qr', 'QR code'), ('biometric', 'Biometric adapter'), ('import', 'Imported')], default='web', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alert_type', models.CharField(choices=[('absence', 'Repeated absence'), ('late', 'Repeated lateness'), ('safeguarding', 'Safeguarding concern'), ('missing', 'Unexplained missing learner')], default='absence', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('summary', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_attendance_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_alerts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('intervention_type', models.CharField(choices=[('call', 'Parent/guardian call'), ('meeting', 'Family meeting'), ('counselling', 'Learner counselling'), ('home_visit', 'Home visit'), ('referral', 'Safeguarding referral'), ('support_plan', 'Attendance support plan')], max_length=24)),
                ('action_date', models.DateField(default=django.utils.timezone.localdate)),
                ('details', models.TextField()),
                ('outcome', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('follow_up', 'Follow-up required')], default='planned', max_length=20)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='attendance.attendancealert')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_interventions', to='students.student')),
            ],
            options={
                'ordering': ['-action_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('qr', 'QR code'), ('biometric', 'Biometric provider'), ('external', 'External system')], max_length=20)),
                ('external_reference', models.CharField(max_length=180)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_attendance_identities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_identities', to='students.student')),
            ],
            options={
                'ordering': ['student', 'provider'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('provider', 'external_reference'), name='unique_attendance_external_identity')],
            },
        ),
    ]
